
# go 1.21.11-2
FROM registry.access.redhat.com/ubi9/go-toolset@sha256:97e30a01caeece72ee967013e7c7af777ea4ee93840681ddcfe38a87eb4c084a as builder 

USER root
WORKDIR /workspace
COPY . .

# renovate: datasource=github-releases depName=pulumi/pulumi
ENV PULUMI_VERSION 3.137.0
ENV PULUMI_URL https://github.com/pulumi/pulumi/releases/download/v${PULUMI_VERSION}/pulumi-v${PULUMI_VERSION}-linux-x64.tar.gz

RUN make build \
    && curl -L ${PULUMI_URL} -o pulumicli.tar.gz \
    && tar -xzvf pulumicli.tar.gz 

# ubi 9.4-1123.1719560047
FROM registry.access.redhat.com/ubi9@sha256:ee0b908e958a1822afc57e5d386d1ea128eebe492cb2e01b6903ee19c133ea75  

LABEL org.opencontainers.image.authors="Redhat Developer"

COPY --from=builder /workspace/out/mapt /workspace/pulumi/pulumi /usr/local/bin/

ENV INTERNAL_OUTPUT=/tmp/mapt \
    PULUMI_CONFIG_PASSPHRASE="passphrase" \
    AWS_SDK_LOAD_CONFIG=1

VOLUME [ "${INTERNAL_OUTPUT}" ]

ENV AWS_CLI_VERSION 2.16.7
ENV AWS_CLI_URL https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWS_CLI_VERSION}.zip

ENV AZ_CLI_VERSION 2.61.0
ENV AZ_CLI_RPM https://packages.microsoft.com/rhel/9.0/prod/Packages/a/azure-cli-${AZ_CLI_VERSION}-1.el9.x86_64.rpm

# Pulumi plugins
# renovate: datasource=github-releases depName=pulumi/pulumi-aws
ARG PULUMI_AWS_VERSION=v6.57.0
# renovate: datasource=github-releases depName=pulumi/pulumi-aws
ARG PULUMI_AWSX_VERSION=v6.57.0
# renovate: datasource=github-releases depName=pulumi/pulumi-azure-native
ARG PULUMI_AZURE_NATIVE_VERSION=v2.69.0
# renovate: datasource=github-releases depName=pulumi/pulumi-command
ARG PULUMI_COMMAND_VERSION=v1.0.1
# renovate: datasource=github-releases depName=pulumi/pulumi-tls
ARG PULUMI_TLS_VERSION=v5.0.3
# renovate: datasource=github-releases depName=pulumi/pulumi-random
ARG PULUMI_RANDOM_VERSION=v4.16.2

RUN curl ${AWS_CLI_URL} -o awscliv2.zip \
    && dnf install -y unzip \
    && unzip awscliv2.zip \
    && ./aws/install \
    && curl -L ${AZ_CLI_RPM} -o azure-cli.rpm \
    && dnf install -y azure-cli.rpm \
    && rm -rf aws awscliv2.zip azure-cli.rpm \
    && dnf clean all \
  	&& rm -rf /var/cache/yum \
    && mkdir -p "${INTERNAL_OUTPUT}" \
    && pulumi plugin install resource aws ${PULUMI_AWS_VERSION} \
    && pulumi plugin install resource awsx ${PULUMI_AWSX_VERSION} \
    && pulumi plugin install resource azure-native ${PULUMI_AZURE_NATIVE_VERSION} \
    && pulumi plugin install resource command ${PULUMI_COMMAND_VERSION} \
    && pulumi plugin install resource tls ${PULUMI_TLS_VERSION} \
    && pulumi plugin install resource random ${PULUMI_RANDOM_VERSION}

# TODO review permissions on sharing mounting volume from host
# USER 65532:65532

ENTRYPOINT ["mapt"]
# Default to show help
CMD ["-h"]

